### ISSUE TITLE
issueレビュー用

### ISSUE THREAD

**Issue by jenida3** [jenida3/portfolio#19]
■Webアプリの概要
「TactiZone」は、は、FPSやTPSといったシューティングゲームにおける「強ポジ」と呼ばれる、戦闘で有利になるポジションや戦術をユーザー同士で共有できるプラットフォームです。 ユーザーは各ゲームのマップ内での有効なポジションや戦略、立ち回りを投稿・閲覧しながらスキル向上を図り、より効率的にゲームを楽しむことができます。 ゲーム初心者から上級者まで、目的に応じた戦略情報を検索・タグ付け機能で迅速に見つけることが可能です。 また、ユーザー同士で意見交換ができる機能や、「いいね」による評価システムを通じて、コミュニティ内で信頼される情報や新しい戦略を発見しやすくなっています。 さらに、マイページで個人の投稿履歴や好みのポジションを管理でき、使えば使うほど効果的な戦略が蓄積されます。 esportsが盛り上がる昨今、より多くの人がゲームを楽しみ、上達の喜びを感じられるサービスとして、多くのプレイヤーの成長をサポートします。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

■ProjectsのURL
https://github.com/users/jenida3/projects/1

■MVPリリースまで
- [ ] rails new
- [ ] renderにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 投稿一覧ページ
- [ ] 投稿機能
- [ ] タグ付け
- [ ] いいね機能
- [ ] 検索機能

■MVP後
- [ ] マイページ
- [ ] お気に入り機能
- [ ] 画像投稿機能
- [ ] パスワードリセット

■MVPレビュー依頼予定日
予定日：2024年 11月 16日

**Comment by tarakish** [comment]
確認できました。LGTMです！
MVPリリースに向けて開発頑張ってください。
